/* Creación tablas CLIENTES */
/* CLIENTES es tabla principal para contactos, direcciones y relaciones */

CREATE TABLE CLIENTES (
  ID_CLIENTE       NUMBER(12)    PRIMARY KEY,
  NOMBRE           VARCHAR2(50)   NOT NULL,
  PRIMER_APELLIDO  VARCHAR2(50)   NOT NULL,
  SEGUNDO_APELLIDO VARCHAR2(50)   NOT NULL
);

CREATE TABLE CORREOS_CLIENTES (
  ID_CORREO_CLIENTE NUMBER(10)   PRIMARY KEY,
  DESCRIPCION       VARCHAR2(100) NOT NULL,
  ID_CLIENTE        NUMBER(12)    NOT NULL,
  CONSTRAINT FK_CORREOS_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE MEDIOS_PREFERIDOS_CLIENTES (
  ID_MEDIO_PREFERIDO NUMBER(10)   PRIMARY KEY,
  DESCRIPCION        VARCHAR2(100) NOT NULL,
  ID_CLIENTE         NUMBER(12)    NOT NULL,
  CONSTRAINT FK_MEDIO_PREF_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE TELEFONOS_CLIENTES (
  ID_TELEFONO_CLIENTE NUMBER(10)  PRIMARY KEY,
  NUMERO_TELEFONO     VARCHAR2(20) NOT NULL,
  ID_CLIENTE          NUMBER(12)   NOT NULL,
  CONSTRAINT FK_TELEFONO_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE DIRECCIONES_CLIENTES (
  ID_DIRECCION  NUMBER(10)    PRIMARY KEY,
  PROVINCIA     VARCHAR2(50)  NOT NULL,
  CANTON        VARCHAR2(50)  NOT NULL,
  DISTRITO      VARCHAR2(50)  NOT NULL,
  SENAS_EXACTAS VARCHAR2(200) NOT NULL,
  ID_CLIENTE    NUMBER(12)    NOT NULL,
  CONSTRAINT FK_DIRECCION_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

/* EVIDENCIA: ver que las tablas quedaron creadas en el esquema */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
  'CLIENTES','CORREOS_CLIENTES','MEDIOS_PREFERIDOS_CLIENTES',
  'TELEFONOS_CLIENTES','DIRECCIONES_CLIENTES'
)
ORDER BY TABLE_NAME;

/***************************/

/* Creación Tablas MASCOTAS */
/* Registrar mascotas y relacionarlas con clientes */

CREATE TABLE MASCOTAS (
  ID_MASCOTA        NUMBER(10)   PRIMARY KEY,
  NOMBRE            VARCHAR2(50)  NOT NULL,
  ESPECIE           VARCHAR2(50)  NOT NULL,
  RAZA              VARCHAR2(50),
  EDAD              NUMBER(3),
  FECHA_NACIMIENTO  DATE,
  ESTADO            VARCHAR2(30),
  SEXO              VARCHAR2(10),
  COLOR             VARCHAR2(30),
  PESO              NUMBER(5,2)
);

CREATE TABLE CLIENTES_MASCOTAS (
  ID_CLIENTE_MASCOTA NUMBER(10) PRIMARY KEY,
  ID_CLIENTE         NUMBER(12) NOT NULL,
  ID_MASCOTA         NUMBER(10) NOT NULL,
  CONSTRAINT FK_CM_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
  CONSTRAINT FK_CM_MASCOTA
    FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA)
);

/* Comando para evitar duplicados de la misma relación cliente-mascota */
ALTER TABLE CLIENTES_MASCOTAS
ADD CONSTRAINT UK_CM_CLIENTE_MASCOTA UNIQUE (ID_CLIENTE, ID_MASCOTA);

/* EVIDENCIA: ver tablas creadas */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN ('MASCOTAS','CLIENTES_MASCOTAS')
ORDER BY TABLE_NAME;

/***************************/

/*Creación de tablas VENTAS */
/* Registrar ventas y asociarlas a clientes */

CREATE TABLE VENTAS (
  ID_VENTA        NUMBER(10)    PRIMARY KEY,
  PRODUCTO        VARCHAR2(100),
  SERVICIO        VARCHAR2(100),
  PRECIO_UNITARIO NUMBER(10,2)  NOT NULL,
  MONTO_TOTAL     NUMBER(10,2)  NOT NULL,
  METODO_PAGO     VARCHAR2(30)  NOT NULL,
  FECHA           DATE          NOT NULL,
  CONSTRAINT CK_VENTAS_PRECIO CHECK (PRECIO_UNITARIO >= 0),
  CONSTRAINT CK_VENTAS_MONTO  CHECK (MONTO_TOTAL >= 0)
);

CREATE TABLE CLIENTES_VENTAS (
  ID_CLIENTE_VENTA NUMBER(10) PRIMARY KEY,
  ID_CLIENTE       NUMBER(12) NOT NULL,
  ID_VENTA         NUMBER(10) NOT NULL,
  CONSTRAINT FK_CV_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
  CONSTRAINT FK_CV_VENTA
    FOREIGN KEY (ID_VENTA) REFERENCES VENTAS(ID_VENTA)
);

/*  Comando para evitar duplicados de la misma relación cliente-venta */
ALTER TABLE CLIENTES_VENTAS
ADD CONSTRAINT UK_CV_CLIENTE_VENTA UNIQUE (ID_CLIENTE, ID_VENTA);

/* EVIDENCIA: ver tablas creadas */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN ('VENTAS','CLIENTES_VENTAS')
ORDER BY TABLE_NAME;

/***************************/
/* Creación de tablas VACUNAS */
/* Registrar vacunas aplicadas a una mascota */

CREATE TABLE VACUNAS (
  ID_VACUNA        NUMBER(10)    PRIMARY KEY,
  TIPO_VACUNA      VARCHAR2(100) NOT NULL,
  LOTE             VARCHAR2(50)  NOT NULL,
  FABRICANTE       VARCHAR2(100) NOT NULL,
  FECHA_APLICACION DATE          NOT NULL,
  PROXIMA_DOSIS    DATE,
  OBSERVACIONES    VARCHAR2(250),
  ID_MASCOTA       NUMBER(10)    NOT NULL,
  CONSTRAINT FK_VACUNA_MASCOTA
    FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA)
);

/* EVIDENCIA: ver tabla creada */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'VACUNAS';

/***************************/

/*Creación tablas MEDICOS */
/* Registrar médicos y su información asociada (contactos, especialidad, horario)*/

CREATE TABLE MEDICOS (
  ID_MEDICO        NUMBER(12)   PRIMARY KEY,
  NOMBRE           VARCHAR2(50)  NOT NULL,
  PRIMER_APELLIDO  VARCHAR2(50)  NOT NULL,
  SEGUNDO_APELLIDO VARCHAR2(50)  NOT NULL
);

CREATE TABLE CORREOS_MEDICOS (
  ID_CORREO_MEDICO NUMBER(10)    PRIMARY KEY,
  DESCRIPCION      VARCHAR2(100) NOT NULL,
  ID_MEDICO        NUMBER(12)    NOT NULL,
  CONSTRAINT FK_CORREO_MEDICO
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);

CREATE TABLE TELEFONOS_MEDICOS (
  ID_TELEFONO_MEDICO NUMBER(10)   PRIMARY KEY,
  NUMERO_TELEFONO    VARCHAR2(20) NOT NULL,
  ID_MEDICO          NUMBER(12)   NOT NULL,
  CONSTRAINT FK_TELEFONO_MEDICO
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);

CREATE TABLE ESPECIALIDADES_MEDICOS (
  ID_ESPECIALIDAD     NUMBER(10)    PRIMARY KEY,
  NOMBRE_ESPECIALIDAD VARCHAR2(100) NOT NULL,
  ID_MEDICO           NUMBER(12)    NOT NULL,
  CONSTRAINT FK_ESPECIALIDAD_MEDICO
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);

CREATE TABLE HORARIOS_MEDICOS (
  ID_HORARIO NUMBER(10)    PRIMARY KEY,
  HORARIO    VARCHAR2(100) NOT NULL,
  ID_MEDICO  NUMBER(12)    NOT NULL,
  CONSTRAINT FK_HORARIO_MEDICO
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);

/* EVIDENCIA: ver tablas creadas */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
  'MEDICOS','CORREOS_MEDICOS','TELEFONOS_MEDICOS',
  'ESPECIALIDADES_MEDICOS','HORARIOS_MEDICOS'
)
ORDER BY TABLE_NAME;

/***************************/

/*Creación tablas CITAS */
/*Agendar citas por mascota y relacionarlas con médicos*/

CREATE TABLE CITAS (
  ID_CITA        NUMBER(10)    PRIMARY KEY,
  FECHA          DATE          NOT NULL,
  HORA           VARCHAR2(8)   NOT NULL,   
  TIPO_CONSULTA  VARCHAR2(100) NOT NULL,
  ESTADO         VARCHAR2(30)  NOT NULL,
  OBSERVACIONES  VARCHAR2(250),
  ID_MASCOTA     NUMBER(10)    NOT NULL,
  CONSTRAINT FK_CITA_MASCOTA
    FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA)
);

CREATE TABLE MEDICOS_CITAS (
  ID_MEDICO_CITA NUMBER(10) PRIMARY KEY,
  ID_MEDICO      NUMBER(12) NOT NULL,
  ID_CITA        NUMBER(10) NOT NULL,
  CONSTRAINT FK_MC_MEDICO
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO),
  CONSTRAINT FK_MC_CITA
    FOREIGN KEY (ID_CITA) REFERENCES CITAS(ID_CITA)
);

/*Comando para evitar duplicados del mismo médico en la misma cita */
ALTER TABLE MEDICOS_CITAS
ADD CONSTRAINT UK_MC_MEDICO_CITA UNIQUE (ID_MEDICO, ID_CITA);

/* EVIDENCIA: ver tablas creadas */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN ('CITAS','MEDICOS_CITAS')
ORDER BY TABLE_NAME;

/***************************/

/*Creación de tablas entre MEDICOS - VACUNAS*/
/*Relacionar qué médico aplicó qué vacuna*/

CREATE TABLE MEDICOS_VACUNAS (
  ID_MEDICO_VACUNA NUMBER(10) PRIMARY KEY,
  ID_MEDICO        NUMBER(12) NOT NULL,
  ID_VACUNA        NUMBER(10) NOT NULL,
  CONSTRAINT FK_MV_MEDICO
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO),
  CONSTRAINT FK_MV_VACUNA
    FOREIGN KEY (ID_VACUNA) REFERENCES VACUNAS(ID_VACUNA)
);

/*Comando para evitar duplicados del mismo médico-vacuna*/
ALTER TABLE MEDICOS_VACUNAS
ADD CONSTRAINT UK_MV_MEDICO_VACUNA UNIQUE (ID_MEDICO, ID_VACUNA);

/*EVIDENCIA: ver tabla creada */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'MEDICOS_VACUNAS';