/* Creación tablas CLIENTES */
/* CLIENTES es tabla principal para contactos, direcciones y relaciones */

CREATE TABLE CLIENTES (
  ID_CLIENTE       NUMBER(12)    PRIMARY KEY,
  NOMBRE           VARCHAR2(50)   NOT NULL,
  PRIMER_APELLIDO  VARCHAR2(50)   NOT NULL,
  SEGUNDO_APELLIDO VARCHAR2(50)   NOT NULL
);

CREATE TABLE CORREOS_CLIENTES (
  ID_CORREO_CLIENTE NUMBER(10)   PRIMARY KEY,
  DESCRIPCION       VARCHAR2(100) NOT NULL,
  ID_CLIENTE        NUMBER(12)    NOT NULL,
  CONSTRAINT FK_CORREOS_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE MEDIOS_PREFERIDOS_CLIENTES (
  ID_MEDIO_PREFERIDO NUMBER(10)   PRIMARY KEY,
  DESCRIPCION        VARCHAR2(100) NOT NULL,
  ID_CLIENTE         NUMBER(12)    NOT NULL,
  CONSTRAINT FK_MEDIO_PREF_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE TELEFONOS_CLIENTES (
  ID_TELEFONO_CLIENTE NUMBER(10)  PRIMARY KEY,
  NUMERO_TELEFONO     VARCHAR2(20) NOT NULL,
  ID_CLIENTE          NUMBER(12)   NOT NULL,
  CONSTRAINT FK_TELEFONO_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE DIRECCIONES_CLIENTES (
  ID_DIRECCION  NUMBER(10)    PRIMARY KEY,
  PROVINCIA     VARCHAR2(50)  NOT NULL,
  CANTON        VARCHAR2(50)  NOT NULL,
  DISTRITO      VARCHAR2(50)  NOT NULL,
  SENAS_EXACTAS VARCHAR2(200) NOT NULL,
  ID_CLIENTE    NUMBER(12)    NOT NULL,
  CONSTRAINT FK_DIRECCION_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

/* EVIDENCIA: ver que las tablas quedaron creadas en el esquema */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
  'CLIENTES','CORREOS_CLIENTES','MEDIOS_PREFERIDOS_CLIENTES',
  'TELEFONOS_CLIENTES','DIRECCIONES_CLIENTES'
)
ORDER BY TABLE_NAME;

***************************

/* Creación Tablas MASCOTAS */
/* Registrar mascotas y relacionarlas con clientes */

CREATE TABLE MASCOTAS (
  ID_MASCOTA        NUMBER(10)   PRIMARY KEY,
  NOMBRE            VARCHAR2(50)  NOT NULL,
  ESPECIE           VARCHAR2(50)  NOT NULL,
  RAZA              VARCHAR2(50),
  EDAD              NUMBER(3),
  FECHA_NACIMIENTO  DATE,
  ESTADO            VARCHAR2(30),
  SEXO              VARCHAR2(10),
  COLOR             VARCHAR2(30),
  PESO              NUMBER(5,2)
);

CREATE TABLE CLIENTES_MASCOTAS (
  ID_CLIENTE_MASCOTA NUMBER(10) PRIMARY KEY,
  ID_CLIENTE         NUMBER(12) NOT NULL,
  ID_MASCOTA         NUMBER(10) NOT NULL,
  CONSTRAINT FK_CM_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
  CONSTRAINT FK_CM_MASCOTA
    FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA)
);

/* Comando para evitar duplicados de la misma relación cliente-mascota */
ALTER TABLE CLIENTES_MASCOTAS
ADD CONSTRAINT UK_CM_CLIENTE_MASCOTA UNIQUE (ID_CLIENTE, ID_MASCOTA);

/* EVIDENCIA: ver tablas creadas */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN ('MASCOTAS','CLIENTES_MASCOTAS')
ORDER BY TABLE_NAME;

***************************

/*Creación de tablas VENTAS */
/* Registrar ventas y asociarlas a clientes */

CREATE TABLE VENTAS (
  ID_VENTA        NUMBER(10)    PRIMARY KEY,
  PRODUCTO        VARCHAR2(100),
  SERVICIO        VARCHAR2(100),
  PRECIO_UNITARIO NUMBER(10,2)  NOT NULL,
  MONTO_TOTAL     NUMBER(10,2)  NOT NULL,
  METODO_PAGO     VARCHAR2(30)  NOT NULL,
  FECHA           DATE          NOT NULL,
  CONSTRAINT CK_VENTAS_PRECIO CHECK (PRECIO_UNITARIO >= 0),
  CONSTRAINT CK_VENTAS_MONTO  CHECK (MONTO_TOTAL >= 0)
);

CREATE TABLE CLIENTES_VENTAS (
  ID_CLIENTE_VENTA NUMBER(10) PRIMARY KEY,
  ID_CLIENTE       NUMBER(12) NOT NULL,
  ID_VENTA         NUMBER(10) NOT NULL,
  CONSTRAINT FK_CV_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
  CONSTRAINT FK_CV_VENTA
    FOREIGN KEY (ID_VENTA) REFERENCES VENTAS(ID_VENTA)
);

/*  Comando para evitar duplicados de la misma relación cliente-venta */
ALTER TABLE CLIENTES_VENTAS
ADD CONSTRAINT UK_CV_CLIENTE_VENTA UNIQUE (ID_CLIENTE, ID_VENTA);

/* EVIDENCIA: ver tablas creadas */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN ('VENTAS','CLIENTES_VENTAS')
ORDER BY TABLE_NAME;

***************************
/* Creación de tablas VACUNAS */
/* Registrar vacunas aplicadas a una mascota */

CREATE TABLE VACUNAS (
  ID_VACUNA        NUMBER(10)    PRIMARY KEY,
  TIPO_VACUNA      VARCHAR2(100) NOT NULL,
  LOTE             VARCHAR2(50)  NOT NULL,
  FABRICANTE       VARCHAR2(100) NOT NULL,
  FECHA_APLICACION DATE          NOT NULL,
  PROXIMA_DOSIS    DATE,
  OBSERVACIONES    VARCHAR2(250),
  ID_MASCOTA       NUMBER(10)    NOT NULL,
  CONSTRAINT FK_VACUNA_MASCOTA
    FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA)
);

/* EVIDENCIA: ver tabla creada */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'VACUNAS';

***************************

/*Creación tablas MEDICOS */
/* Registrar médicos y su información asociada (contactos, especialidad, horario)*/

CREATE TABLE MEDICOS (
  ID_MEDICO        NUMBER(12)   PRIMARY KEY,
  NOMBRE           VARCHAR2(50)  NOT NULL,
  PRIMER_APELLIDO  VARCHAR2(50)  NOT NULL,
  SEGUNDO_APELLIDO VARCHAR2(50)  NOT NULL
);

CREATE TABLE CORREOS_MEDICOS (
  ID_CORREO_MEDICO NUMBER(10)    PRIMARY KEY,
  DESCRIPCION      VARCHAR2(100) NOT NULL,
  ID_MEDICO        NUMBER(12)    NOT NULL,
  CONSTRAINT FK_CORREO_MEDICO
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);

CREATE TABLE TELEFONOS_MEDICOS (
  ID_TELEFONO_MEDICO NUMBER(10)   PRIMARY KEY,
  NUMERO_TELEFONO    VARCHAR2(20) NOT NULL,
  ID_MEDICO          NUMBER(12)   NOT NULL,
  CONSTRAINT FK_TELEFONO_MEDICO
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);

CREATE TABLE ESPECIALIDADES_MEDICOS (
  ID_ESPECIALIDAD     NUMBER(10)    PRIMARY KEY,
  NOMBRE_ESPECIALIDAD VARCHAR2(100) NOT NULL,
  ID_MEDICO           NUMBER(12)    NOT NULL,
  CONSTRAINT FK_ESPECIALIDAD_MEDICO
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);

CREATE TABLE HORARIOS_MEDICOS (
  ID_HORARIO NUMBER(10)    PRIMARY KEY,
  HORARIO    VARCHAR2(100) NOT NULL,
  ID_MEDICO  NUMBER(12)    NOT NULL,
  CONSTRAINT FK_HORARIO_MEDICO
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);

/* EVIDENCIA: ver tablas creadas */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
  'MEDICOS','CORREOS_MEDICOS','TELEFONOS_MEDICOS',
  'ESPECIALIDADES_MEDICOS','HORARIOS_MEDICOS'
)
ORDER BY TABLE_NAME;

***************************

/*Creación tablas CITAS */
/*Agendar citas por mascota y relacionarlas con médicos*/

CREATE TABLE CITAS (
  ID_CITA        NUMBER(10)    PRIMARY KEY,
  FECHA          DATE          NOT NULL,
  HORA           VARCHAR2(8)   NOT NULL,   
  TIPO_CONSULTA  VARCHAR2(100) NOT NULL,
  ESTADO         VARCHAR2(30)  NOT NULL,
  OBSERVACIONES  VARCHAR2(250),
  ID_MASCOTA     NUMBER(10)    NOT NULL,
  CONSTRAINT FK_CITA_MASCOTA
    FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA)
);

CREATE TABLE MEDICOS_CITAS (
  ID_MEDICO_CITA NUMBER(10) PRIMARY KEY,
  ID_MEDICO      NUMBER(12) NOT NULL,
  ID_CITA        NUMBER(10) NOT NULL,
  CONSTRAINT FK_MC_MEDICO
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO),
  CONSTRAINT FK_MC_CITA
    FOREIGN KEY (ID_CITA) REFERENCES CITAS(ID_CITA)
);

/*Comando para evitar duplicados del mismo médico en la misma cita */
ALTER TABLE MEDICOS_CITAS
ADD CONSTRAINT UK_MC_MEDICO_CITA UNIQUE (ID_MEDICO, ID_CITA);

/* EVIDENCIA: ver tablas creadas */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN ('CITAS','MEDICOS_CITAS')
ORDER BY TABLE_NAME;

***************************

/*Creación de tablas entre MEDICOS - VACUNAS*/
/*Relacionar qué médico aplicó qué vacuna*/

CREATE TABLE MEDICOS_VACUNAS (
  ID_MEDICO_VACUNA NUMBER(10) PRIMARY KEY,
  ID_MEDICO        NUMBER(12) NOT NULL,
  ID_VACUNA        NUMBER(10) NOT NULL,
  CONSTRAINT FK_MV_MEDICO
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO),
  CONSTRAINT FK_MV_VACUNA
    FOREIGN KEY (ID_VACUNA) REFERENCES VACUNAS(ID_VACUNA)
);

/*Comando para evitar duplicados del mismo médico-vacuna*/
ALTER TABLE MEDICOS_VACUNAS
ADD CONSTRAINT UK_MV_MEDICO_VACUNA UNIQUE (ID_MEDICO, ID_VACUNA);

/*EVIDENCIA: ver tabla creada */
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'MEDICOS_VACUNAS';

***************************

/*Creación de tabla Usuario */
SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE USUARIO (
  ID_USUARIO      NUMBER(10)    PRIMARY KEY,
  NOMBRE          VARCHAR2(50)  NOT NULL,
  APELLIDO        VARCHAR2(50)  NOT NULL,
  NOMBRE_USUARIO  VARCHAR2(50)  NOT NULL UNIQUE,
  CONTRASENA      VARCHAR2(100) NOT NULL,
  ROL             VARCHAR2(30)  DEFAULT 'OPERADOR' NOT NULL
);

/*Secuencias*/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CORREO_CLIENTE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_CORREO_CLIENTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TELEFONO_CLIENTE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_TELEFONO_CLIENTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTE_MASCOTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_CLIENTE_MASCOTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTE_VENTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_CLIENTE_VENTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MEDICO_CITA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_MEDICO_CITA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MEDICO_VACUNA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_MEDICO_VACUNA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

/*SP */
CREATE OR REPLACE PROCEDURE SP_REGISTRAR_USUARIO (
  P_NOMBRE     IN VARCHAR2,
  P_APELLIDO   IN VARCHAR2,
  P_USERNAME   IN VARCHAR2,
  P_PASS       IN VARCHAR2,
  P_ROL        IN VARCHAR2 DEFAULT 'OPERADOR'
)
IS
  V_ID NUMBER;
BEGIN
  IF P_NOMBRE IS NULL OR TRIM(P_NOMBRE) = '' THEN
    RAISE_APPLICATION_ERROR(-20010, 'El nombre no puede estar vacío');
  ELSIF P_APELLIDO IS NULL OR TRIM(P_APELLIDO) = '' THEN
    RAISE_APPLICATION_ERROR(-20011, 'El apellido no puede estar vacío');
  ELSIF P_USERNAME IS NULL OR TRIM(P_USERNAME) = '' THEN
    RAISE_APPLICATION_ERROR(-20012, 'El usuario no puede estar vacío');
  ELSIF P_PASS IS NULL OR TRIM(P_PASS) = '' THEN
    RAISE_APPLICATION_ERROR(-20013, 'La contraseña no puede estar vacía');
  END IF;

  V_ID := SEQ_USUARIO.NEXTVAL;

  INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO, NOMBRE_USUARIO, CONTRASENA, ROL)
  VALUES (V_ID, P_NOMBRE, P_APELLIDO, P_USERNAME, P_PASS, NVL(P_ROL,'OPERADOR'));

  DBMS_OUTPUT.PUT_LINE('Usuario registrado. ID=' || V_ID);
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    RAISE_APPLICATION_ERROR(-20014, 'Ya existe un usuario con ese nombre');
END;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_USUARIO (
  P_ID        IN NUMBER,
  P_NOMBRE    IN VARCHAR2,
  P_APELLIDO  IN VARCHAR2,
  P_ROL       IN VARCHAR2
)
IS
BEGIN
  UPDATE USUARIO
  SET NOMBRE = P_NOMBRE,
      APELLIDO = P_APELLIDO,
      ROL = P_ROL
  WHERE ID_USUARIO = P_ID;

  IF SQL%ROWCOUNT = 0 THEN
    RAISE_APPLICATION_ERROR(-20022, 'No existe un usuario con ese ID');
  END IF;

  DBMS_OUTPUT.PUT_LINE('Usuario actualizado');
END;
/

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_USUARIO (
  P_ID IN NUMBER
)
IS
BEGIN
  DELETE FROM USUARIO WHERE ID_USUARIO = P_ID;

  IF SQL%ROWCOUNT = 0 THEN
    RAISE_APPLICATION_ERROR(-20023, 'No existe un usuario con ese ID');
  END IF;

  DBMS_OUTPUT.PUT_LINE('Usuario eliminado');
END;
/

CREATE OR REPLACE PROCEDURE SP_LOGIN_USUARIO (
  P_USERNAME   IN  VARCHAR2,
  P_PASS       IN  VARCHAR2,
  P_OK         OUT NUMBER,
  P_ROL        OUT VARCHAR2
)
IS
BEGIN
  SELECT CASE WHEN COUNT(*) = 1 THEN 1 ELSE 0 END,
         MAX(ROL)
  INTO P_OK, P_ROL
  FROM USUARIO
  WHERE NOMBRE_USUARIO = P_USERNAME
    AND CONTRASENA = P_PASS;
END;
/

CREATE OR REPLACE PROCEDURE SP_LISTAR_USUARIOS (
  P_CURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN P_CURSOR FOR
    SELECT ID_USUARIO, NOMBRE_USUARIO, ROL
    FROM USUARIO
    ORDER BY ID_USUARIO;
END;
/

CREATE OR REPLACE PROCEDURE SP_BUSCAR_USUARIO (
  P_TEXTO   IN VARCHAR2,
  P_CURSOR  OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN P_CURSOR FOR
    SELECT ID_USUARIO, NOMBRE_USUARIO, ROL
    FROM USUARIO
    WHERE TO_CHAR(ID_USUARIO) LIKE '%'||P_TEXTO||'%'
       OR UPPER(NOMBRE_USUARIO) LIKE UPPER('%'||P_TEXTO||'%')
       OR UPPER(ROL) LIKE UPPER('%'||P_TEXTO||'%')
    ORDER BY ID_USUARIO;
END;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_CLIENTE (
  P_ID         IN NUMBER,
  P_NOMBRE     IN VARCHAR2,
  P_APELLIDO1  IN VARCHAR2,
  P_APELLIDO2  IN VARCHAR2,
  P_CORREO     IN VARCHAR2,
  P_TELEFONO   IN VARCHAR2
)
IS
BEGIN
  IF P_NOMBRE IS NULL OR TRIM(P_NOMBRE) = '' THEN
    RAISE_APPLICATION_ERROR(-20030, 'El nombre del cliente no puede estar vacío');
  ELSIF P_APELLIDO1 IS NULL OR TRIM(P_APELLIDO1) = '' THEN
    RAISE_APPLICATION_ERROR(-20031, 'El primer apellido no puede estar vacío');
  ELSIF P_APELLIDO2 IS NULL OR TRIM(P_APELLIDO2) = '' THEN
    RAISE_APPLICATION_ERROR(-20032, 'El segundo apellido no puede estar vacío');
  END IF;

  INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO)
  VALUES (P_ID, P_NOMBRE, P_APELLIDO1, P_APELLIDO2);

  INSERT INTO CORREOS_CLIENTES (ID_CORREO_CLIENTE, DESCRIPCION, ID_CLIENTE)
  VALUES (SEQ_CORREO_CLIENTE.NEXTVAL, P_CORREO, P_ID);

  INSERT INTO TELEFONOS_CLIENTES (ID_TELEFONO_CLIENTE, NUMERO_TELEFONO, ID_CLIENTE)
  VALUES (SEQ_TELEFONO_CLIENTE.NEXTVAL, P_TELEFONO, P_ID);

  DBMS_OUTPUT.PUT_LINE('Cliente registrado');
END;
/

/*FUNCIONES*/
CREATE OR REPLACE FUNCTION FN_TOTAL_GASTADO (P_ID_CLIENTE NUMBER)
RETURN NUMBER
IS
  V_TOTAL NUMBER;
BEGIN
  SELECT NVL(SUM(V.MONTO_TOTAL), 0)
  INTO V_TOTAL
  FROM CLIENTES_VENTAS CV
  JOIN VENTAS V ON CV.ID_VENTA = V.ID_VENTA
  WHERE CV.ID_CLIENTE = P_ID_CLIENTE;

  RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_EDAD_MASCOTA (P_ID_MASCOTA NUMBER)
RETURN NUMBER
IS
  V_FECHA DATE;
BEGIN
  SELECT FECHA_NACIMIENTO
  INTO V_FECHA
  FROM MASCOTAS
  WHERE ID_MASCOTA = P_ID_MASCOTA;

  RETURN TRUNC(MONTHS_BETWEEN(SYSDATE, V_FECHA) / 12);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;
/

/*TRIGERS*/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_FECHA_CITA
BEFORE INSERT OR UPDATE ON CITAS
FOR EACH ROW
DECLARE
  V_EXISTE NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO V_EXISTE
  FROM CITAS
  WHERE ID_MASCOTA = :NEW.ID_MASCOTA
    AND TRUNC(FECHA) = TRUNC(:NEW.FECHA)
    AND HORA = :NEW.HORA
    AND ID_CITA != NVL(:NEW.ID_CITA, -1);

  IF V_EXISTE > 0 THEN
    RAISE_APPLICATION_ERROR(-20040, 'Ya existe una cita para esa mascota en esa fecha y hora');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_CORREO_CLIENTE
BEFORE INSERT OR UPDATE ON CORREOS_CLIENTES
FOR EACH ROW
BEGIN
  IF NOT REGEXP_LIKE(:NEW.DESCRIPCION, '^.*@.*\..*$') THEN
    RAISE_APPLICATION_ERROR(-20041, 'El correo del cliente no tiene un formato válido');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_TELEFONO_CLIENTE
BEFORE INSERT OR UPDATE ON TELEFONOS_CLIENTES
FOR EACH ROW
BEGIN
  IF NOT REGEXP_LIKE(:NEW.NUMERO_TELEFONO, '^\d{8}$') THEN
    RAISE_APPLICATION_ERROR(-20042, 'El teléfono del cliente debe tener 8 dígitos');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_CORREO_MEDICO
BEFORE INSERT OR UPDATE ON CORREOS_MEDICOS
FOR EACH ROW
BEGIN
  IF NOT REGEXP_LIKE(:NEW.DESCRIPCION, '^.*@.*\..*$') THEN
    RAISE_APPLICATION_ERROR(-20043, 'El correo del médico no tiene un formato válido');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_TELEFONO_MEDICO
BEFORE INSERT OR UPDATE ON TELEFONOS_MEDICOS
FOR EACH ROW
BEGIN
  IF NOT REGEXP_LIKE(:NEW.NUMERO_TELEFONO, '^\d{8}$') THEN
    RAISE_APPLICATION_ERROR(-20044, 'El teléfono del médico debe tener 8 dígitos');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_PESO_MASCOTA
BEFORE INSERT OR UPDATE ON MASCOTAS
FOR EACH ROW
BEGIN
  IF :NEW.PESO IS NOT NULL AND :NEW.PESO <= 0 THEN
    RAISE_APPLICATION_ERROR(-20045, 'El peso de la mascota debe ser mayor a cero');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_FECHA_VACUNA
BEFORE INSERT OR UPDATE ON VACUNAS
FOR EACH ROW
BEGIN
  IF TRUNC(:NEW.FECHA_APLICACION) > TRUNC(SYSDATE) THEN
    RAISE_APPLICATION_ERROR(-20046, 'La fecha de aplicación no puede ser futura');
  END IF;
END;
/

/*SP Cliente, registro*/
CREATE OR REPLACE PROCEDURE SP_REGISTRAR_CLIENTE (
  P_ID         IN NUMBER,
  P_NOMBRE     IN VARCHAR2,
  P_APELLIDO1  IN VARCHAR2,
  P_APELLIDO2  IN VARCHAR2,
  P_CORREO     IN VARCHAR2,
  P_TELEFONO   IN VARCHAR2
)
IS
BEGIN
  IF P_NOMBRE IS NULL OR TRIM(P_NOMBRE) = '' THEN
    RAISE_APPLICATION_ERROR(-20030, 'El nombre del cliente no puede estar vacío');
  ELSIF P_APELLIDO1 IS NULL OR TRIM(P_APELLIDO1) = '' THEN
    RAISE_APPLICATION_ERROR(-20031, 'El primer apellido no puede estar vacío');
  ELSIF P_APELLIDO2 IS NULL OR TRIM(P_APELLIDO2) = '' THEN
    RAISE_APPLICATION_ERROR(-20032, 'El segundo apellido no puede estar vacío');
  END IF;

  INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO)
  VALUES (P_ID, P_NOMBRE, P_APELLIDO1, P_APELLIDO2);

  INSERT INTO CORREOS_CLIENTES (ID_CORREO_CLIENTE, DESCRIPCION, ID_CLIENTE)
  VALUES (SEQ_CORREO_CLIENTE.NEXTVAL, P_CORREO, P_ID);

  INSERT INTO TELEFONOS_CLIENTES (ID_TELEFONO_CLIENTE, NUMERO_TELEFONO, ID_CLIENTE)
  VALUES (SEQ_TELEFONO_CLIENTE.NEXTVAL, P_TELEFONO, P_ID);

  DBMS_OUTPUT.PUT_LINE('Cliente registrado');
END;
/

/*Funciones, reportes*/
CREATE OR REPLACE FUNCTION FN_TOTAL_GASTADO (P_ID_CLIENTE NUMBER)
RETURN NUMBER
IS
  V_TOTAL NUMBER;
BEGIN
  SELECT NVL(SUM(V.MONTO_TOTAL), 0)
  INTO V_TOTAL
  FROM CLIENTES_VENTAS CV
  JOIN VENTAS V ON CV.ID_VENTA = V.ID_VENTA
  WHERE CV.ID_CLIENTE = P_ID_CLIENTE;

  RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_EDAD_MASCOTA (P_ID_MASCOTA NUMBER)
RETURN NUMBER
IS
  V_FECHA DATE;
BEGIN
  SELECT FECHA_NACIMIENTO
  INTO V_FECHA
  FROM MASCOTAS
  WHERE ID_MASCOTA = P_ID_MASCOTA;

  RETURN TRUNC(MONTHS_BETWEEN(SYSDATE, V_FECHA) / 12);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;
/

/*TRIGERS validaciones*/
CREATE OR REPLACE TRIGGER TRG_VALIDAR_FECHA_CITA
BEFORE INSERT OR UPDATE ON CITAS
FOR EACH ROW
DECLARE
  V_EXISTE NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO V_EXISTE
  FROM CITAS
  WHERE ID_MASCOTA = :NEW.ID_MASCOTA
    AND TRUNC(FECHA) = TRUNC(:NEW.FECHA)
    AND HORA = :NEW.HORA
    AND ID_CITA != NVL(:NEW.ID_CITA, -1);

  IF V_EXISTE > 0 THEN
    RAISE_APPLICATION_ERROR(-20040, 'Ya existe una cita para esa mascota en esa fecha y hora');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_CORREO_CLIENTE
BEFORE INSERT OR UPDATE ON CORREOS_CLIENTES
FOR EACH ROW
BEGIN
  IF NOT REGEXP_LIKE(:NEW.DESCRIPCION, '^.*@.*\..*$') THEN
    RAISE_APPLICATION_ERROR(-20041, 'El correo del cliente no tiene un formato válido');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_TELEFONO_CLIENTE
BEFORE INSERT OR UPDATE ON TELEFONOS_CLIENTES
FOR EACH ROW
BEGIN
  IF NOT REGEXP_LIKE(:NEW.NUMERO_TELEFONO, '^\d{8}$') THEN
    RAISE_APPLICATION_ERROR(-20042, 'El teléfono del cliente debe tener 8 dígitos');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_CORREO_MEDICO
BEFORE INSERT OR UPDATE ON CORREOS_MEDICOS
FOR EACH ROW
BEGIN
  IF NOT REGEXP_LIKE(:NEW.DESCRIPCION, '^.*@.*\..*$') THEN
    RAISE_APPLICATION_ERROR(-20043, 'El correo del médico no tiene un formato válido');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_TELEFONO_MEDICO
BEFORE INSERT OR UPDATE ON TELEFONOS_MEDICOS
FOR EACH ROW
BEGIN
  IF NOT REGEXP_LIKE(:NEW.NUMERO_TELEFONO, '^\d{8}$') THEN
    RAISE_APPLICATION_ERROR(-20044, 'El teléfono del médico debe tener 8 dígitos');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_PESO_MASCOTA
BEFORE INSERT OR UPDATE ON MASCOTAS
FOR EACH ROW
BEGIN
  IF :NEW.PESO IS NOT NULL AND :NEW.PESO <= 0 THEN
    RAISE_APPLICATION_ERROR(-20045, 'El peso de la mascota debe ser mayor a cero');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_FECHA_VACUNA
BEFORE INSERT OR UPDATE ON VACUNAS
FOR EACH ROW
BEGIN
  IF TRUNC(:NEW.FECHA_APLICACION) > TRUNC(SYSDATE) THEN
    RAISE_APPLICATION_ERROR(-20046, 'La fecha de aplicación no puede ser futura');
  END IF;
END;
/

/*SP, CITAS. Registrar, consultar actualizar, eliminar*/
CREATE OR REPLACE PROCEDURE SP_AGENDAR_CITA (
  P_ID_CITA       IN NUMBER,
  P_FECHA         IN DATE,
  P_HORA          IN VARCHAR2,
  P_TIPO_CONSULTA IN VARCHAR2,
  P_OBSERVACIONES IN VARCHAR2,
  P_ID_MASCOTA    IN NUMBER,
  P_ID_MEDICO     IN NUMBER
)
IS
  V_EXISTE_MASCOTA NUMBER;
  V_EXISTE_MEDICO  NUMBER;
BEGIN
  IF P_FECHA IS NULL THEN
    RAISE_APPLICATION_ERROR(-20052, 'La fecha no puede estar vacía');
  END IF;

  IF TRUNC(P_FECHA) < TRUNC(SYSDATE) THEN
    RAISE_APPLICATION_ERROR(-20053, 'No se puede agendar una cita en fecha pasada');
  END IF;

  SELECT COUNT(*) INTO V_EXISTE_MASCOTA FROM MASCOTAS WHERE ID_MASCOTA = P_ID_MASCOTA;
  IF V_EXISTE_MASCOTA = 0 THEN
    RAISE_APPLICATION_ERROR(-20054, 'No existe una mascota con ese ID');
  END IF;

  SELECT COUNT(*) INTO V_EXISTE_MEDICO FROM MEDICOS WHERE ID_MEDICO = P_ID_MEDICO;
  IF V_EXISTE_MEDICO = 0 THEN
    RAISE_APPLICATION_ERROR(-20055, 'No existe un médico con ese ID');
  END IF;

  INSERT INTO CITAS (ID_CITA, FECHA, HORA, TIPO_CONSULTA, ESTADO, OBSERVACIONES, ID_MASCOTA)
  VALUES (P_ID_CITA, P_FECHA, P_HORA, P_TIPO_CONSULTA, 'Programada', P_OBSERVACIONES, P_ID_MASCOTA);

  INSERT INTO MEDICOS_CITAS (ID_MEDICO_CITA, ID_MEDICO, ID_CITA)
  VALUES (SEQ_MEDICO_CITA.NEXTVAL, P_ID_MEDICO, P_ID_CITA);
END;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_CITA (
  P_ID_CITA       IN NUMBER,
  P_FECHA         IN DATE,
  P_HORA          IN VARCHAR2,
  P_TIPO_CONSULTA IN VARCHAR2,
  P_ESTADO        IN VARCHAR2,
  P_OBSERVACIONES IN VARCHAR2
)
IS
BEGIN
  UPDATE CITAS
  SET FECHA = P_FECHA,
      HORA = P_HORA,
      TIPO_CONSULTA = P_TIPO_CONSULTA,
      ESTADO = P_ESTADO,
      OBSERVACIONES = P_OBSERVACIONES
  WHERE ID_CITA = P_ID_CITA;

  IF SQL%ROWCOUNT = 0 THEN
    RAISE_APPLICATION_ERROR(-20064, 'No existe una cita con ese ID');
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_CITA (
  P_ID_CITA IN NUMBER
)
IS
BEGIN
  DELETE FROM MEDICOS_CITAS WHERE ID_CITA = P_ID_CITA;
  DELETE FROM CITAS WHERE ID_CITA = P_ID_CITA;

  IF SQL%ROWCOUNT = 0 THEN
    RAISE_APPLICATION_ERROR(-20070, 'No existe una cita con ese ID');
  END IF;
END;
/

/* Consultar Citas con filtros (se va a devolver cursor para llenar) */
CREATE OR REPLACE PROCEDURE SP_BUSCAR_CITAS (
  P_ID_CITA       IN NUMBER   DEFAULT NULL,
  P_ID_CLIENTE    IN NUMBER   DEFAULT NULL,
  P_ID_MEDICO     IN NUMBER   DEFAULT NULL,
  P_FECHA         IN DATE     DEFAULT NULL,
  P_TIPO_CONSULTA IN VARCHAR2 DEFAULT NULL,
  P_ID_MASCOTA    IN NUMBER   DEFAULT NULL,
  P_CURSOR        OUT SYS_REFCURSOR
)
IS
  V_SQL   VARCHAR2(4000);
BEGIN
  V_SQL :=
    'SELECT C.ID_CITA, C.FECHA, C.HORA, C.TIPO_CONSULTA, C.ESTADO, C.OBSERVACIONES, ' ||
    'C.ID_MASCOTA, MC.ID_MEDICO, CM.ID_CLIENTE ' ||
    'FROM CITAS C ' ||
    'LEFT JOIN MEDICOS_CITAS MC ON C.ID_CITA = MC.ID_CITA ' ||
    'LEFT JOIN CLIENTES_MASCOTAS CM ON C.ID_MASCOTA = CM.ID_MASCOTA ' ||
    'WHERE 1=1 ';

  IF P_ID_CITA IS NOT NULL THEN
    V_SQL := V_SQL || ' AND C.ID_CITA = ' || P_ID_CITA;
  END IF;

  IF P_ID_CLIENTE IS NOT NULL THEN
    V_SQL := V_SQL || ' AND CM.ID_CLIENTE = ' || P_ID_CLIENTE;
  END IF;

  IF P_ID_MEDICO IS NOT NULL THEN
    V_SQL := V_SQL || ' AND MC.ID_MEDICO = ' || P_ID_MEDICO;
  END IF;

  IF P_FECHA IS NOT NULL THEN
    V_SQL := V_SQL || ' AND TRUNC(C.FECHA) = TO_DATE(''' || TO_CHAR(P_FECHA, 'YYYY-MM-DD') || ''',''YYYY-MM-DD'')';
  END IF;

  IF P_TIPO_CONSULTA IS NOT NULL THEN
    V_SQL := V_SQL || ' AND UPPER(C.TIPO_CONSULTA) LIKE UPPER(''%' || REPLACE(P_TIPO_CONSULTA,'''','''''') || '%'')';
  END IF;

  IF P_ID_MASCOTA IS NOT NULL THEN
    V_SQL := V_SQL || ' AND C.ID_MASCOTA = ' || P_ID_MASCOTA;
  END IF;

  OPEN P_CURSOR FOR V_SQL;
END;
/

/*SP REGISTROS MASCOTA, VENTA, VACUNA*/
CREATE OR REPLACE PROCEDURE SP_REGISTRAR_MASCOTA (
  P_ID_MASCOTA       IN NUMBER,
  P_NOMBRE           IN VARCHAR2,
  P_ESPECIE          IN VARCHAR2,
  P_RAZA             IN VARCHAR2,
  P_FECHA_NACIMIENTO IN DATE,
  P_SEXO             IN VARCHAR2,
  P_COLOR            IN VARCHAR2,
  P_PESO             IN NUMBER,
  P_ID_CLIENTE       IN NUMBER
)
IS
  V_EXISTE_CLIENTE NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_EXISTE_CLIENTE FROM CLIENTES WHERE ID_CLIENTE = P_ID_CLIENTE;
  IF V_EXISTE_CLIENTE = 0 THEN
    RAISE_APPLICATION_ERROR(-20083, 'No existe un cliente con ese ID');
  END IF;

  INSERT INTO MASCOTAS (ID_MASCOTA, NOMBRE, ESPECIE, RAZA, FECHA_NACIMIENTO, ESTADO, SEXO, COLOR, PESO)
  VALUES (P_ID_MASCOTA, P_NOMBRE, P_ESPECIE, P_RAZA, P_FECHA_NACIMIENTO, 'Activo', P_SEXO, P_COLOR, P_PESO);

  INSERT INTO CLIENTES_MASCOTAS (ID_CLIENTE_MASCOTA, ID_CLIENTE, ID_MASCOTA)
  VALUES (SEQ_CLIENTE_MASCOTA.NEXTVAL, P_ID_CLIENTE, P_ID_MASCOTA);
END;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_VENTA (
  P_ID_VENTA        IN NUMBER,
  P_PRODUCTO        IN VARCHAR2,
  P_SERVICIO        IN VARCHAR2,
  P_PRECIO_UNITARIO IN NUMBER,
  P_MONTO_TOTAL     IN NUMBER,
  P_METODO_PAGO     IN VARCHAR2,
  P_ID_CLIENTE      IN NUMBER
)
IS
  V_EXISTE_CLIENTE NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_EXISTE_CLIENTE FROM CLIENTES WHERE ID_CLIENTE = P_ID_CLIENTE;
  IF V_EXISTE_CLIENTE = 0 THEN
    RAISE_APPLICATION_ERROR(-20104, 'No existe un cliente con ese ID');
  END IF;

  INSERT INTO VENTAS (ID_VENTA, PRODUCTO, SERVICIO, PRECIO_UNITARIO, MONTO_TOTAL, METODO_PAGO, FECHA)
  VALUES (P_ID_VENTA, P_PRODUCTO, P_SERVICIO, P_PRECIO_UNITARIO, P_MONTO_TOTAL, P_METODO_PAGO, SYSDATE);

  INSERT INTO CLIENTES_VENTAS (ID_CLIENTE_VENTA, ID_CLIENTE, ID_VENTA)
  VALUES (SEQ_CLIENTE_VENTA.NEXTVAL, P_ID_CLIENTE, P_ID_VENTA);
END;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_VACUNA (
  P_ID_VACUNA     IN NUMBER,
  P_TIPO_VACUNA   IN VARCHAR2,
  P_LOTE          IN VARCHAR2,
  P_FABRICANTE    IN VARCHAR2,
  P_PROXIMA_DOSIS IN DATE,
  P_OBSERVACIONES IN VARCHAR2,
  P_ID_MASCOTA    IN NUMBER,
  P_ID_MEDICO     IN NUMBER
)
IS
  V_EXISTE_MASCOTA NUMBER;
  V_EXISTE_MEDICO  NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_EXISTE_MASCOTA FROM MASCOTAS WHERE ID_MASCOTA = P_ID_MASCOTA;
  IF V_EXISTE_MASCOTA = 0 THEN
    RAISE_APPLICATION_ERROR(-20113, 'No existe una mascota con ese ID');
  END IF;

  SELECT COUNT(*) INTO V_EXISTE_MEDICO FROM MEDICOS WHERE ID_MEDICO = P_ID_MEDICO;
  IF V_EXISTE_MEDICO = 0 THEN
    RAISE_APPLICATION_ERROR(-20114, 'No existe un médico con ese ID');
  END IF;

  INSERT INTO VACUNAS (ID_VACUNA, TIPO_VACUNA, LOTE, FABRICANTE, FECHA_APLICACION, PROXIMA_DOSIS, OBSERVACIONES, ID_MASCOTA)
  VALUES (P_ID_VACUNA, P_TIPO_VACUNA, P_LOTE, P_FABRICANTE, SYSDATE, P_PROXIMA_DOSIS, P_OBSERVACIONES, P_ID_MASCOTA);

  INSERT INTO MEDICOS_VACUNAS (ID_MEDICO_VACUNA, ID_MEDICO, ID_VACUNA)
  VALUES (SEQ_MEDICO_VACUNA.NEXTVAL, P_ID_MEDICO, P_ID_VACUNA);
END;
/

/*GRANTS para HP_OPERADOR. Java se conecta con este usuario*/
GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENTES TO HP_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON CORREOS_CLIENTES TO HP_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON TELEFONOS_CLIENTES TO HP_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DIRECCIONES_CLIENTES TO HP_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON MEDIOS_PREFERIDOS_CLIENTES TO HP_OPERADOR;

GRANT SELECT, INSERT, UPDATE, DELETE ON MASCOTAS TO HP_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENTES_MASCOTAS TO HP_OPERADOR;

GRANT SELECT, INSERT, UPDATE, DELETE ON MEDICOS TO HP_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON CORREOS_MEDICOS TO HP_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON TELEFONOS_MEDICOS TO HP_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON ESPECIALIDADES_MEDICOS TO HP_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HORARIOS_MEDICOS TO HP_OPERADOR;

GRANT SELECT, INSERT, UPDATE, DELETE ON CITAS TO HP_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON MEDICOS_CITAS TO HP_OPERADOR;

GRANT SELECT, INSERT, UPDATE, DELETE ON VACUNAS TO HP_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON MEDICOS_VACUNAS TO HP_OPERADOR;

GRANT SELECT, INSERT, UPDATE, DELETE ON VENTAS TO HP_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENTES_VENTAS TO HP_OPERADOR;

GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIO TO HP_OPERADOR;

GRANT EXECUTE ON SP_REGISTRAR_USUARIO TO HP_OPERADOR;
GRANT EXECUTE ON SP_ACTUALIZAR_USUARIO TO HP_OPERADOR;
GRANT EXECUTE ON SP_ELIMINAR_USUARIO TO HP_OPERADOR;
GRANT EXECUTE ON SP_LOGIN_USUARIO TO HP_OPERADOR;
GRANT EXECUTE ON SP_LISTAR_USUARIOS TO HP_OPERADOR;
GRANT EXECUTE ON SP_BUSCAR_USUARIO TO HP_OPERADOR;

GRANT EXECUTE ON SP_REGISTRAR_CLIENTE TO HP_OPERADOR;

GRANT EXECUTE ON SP_AGENDAR_CITA TO HP_OPERADOR;
GRANT EXECUTE ON SP_ACTUALIZAR_CITA TO HP_OPERADOR;
GRANT EXECUTE ON SP_ELIMINAR_CITA TO HP_OPERADOR;
GRANT EXECUTE ON SP_BUSCAR_CITAS TO HP_OPERADOR;

GRANT EXECUTE ON SP_REGISTRAR_MASCOTA TO HP_OPERADOR;
GRANT EXECUTE ON SP_REGISTRAR_VENTA TO HP_OPERADOR;
GRANT EXECUTE ON SP_REGISTRAR_VACUNA TO HP_OPERADOR;

GRANT EXECUTE ON FN_TOTAL_GASTADO TO HP_OPERADOR;
GRANT EXECUTE ON FN_EDAD_MASCOTA TO HP_OPERADOR;

CREATE OR REPLACE VIEW VW_RESUMEN_SISTEMA AS
SELECT 
    c.ID_CLIENTE,
    c.NOMBRE || ' ' || c.PRIMER_APELLIDO || ' ' || c.SEGUNDO_APELLIDO AS CLIENTE,

    m.ID_MASCOTA,
    m.NOMBRE AS MASCOTA,
    m.ESPECIE,
    m.RAZA,

    med.ID_MEDICO,
    med.NOMBRE || ' ' || med.PRIMER_APELLIDO AS MEDICO,

    v.ID_VENTA,
    v.PRODUCTO,
    v.MONTO_TOTAL,

    ci.ID_CITA,
    ci.FECHA,
    ci.TIPO_CONSULTA,
    ci.ESTADO
FROM CLIENTES c
LEFT JOIN CLIENTES_MASCOTAS cm 
    ON c.ID_CLIENTE = cm.ID_CLIENTE
LEFT JOIN MASCOTAS m 
    ON cm.ID_MASCOTA = m.ID_MASCOTA
LEFT JOIN CLIENTES_VENTAS cv 
    ON c.ID_CLIENTE = cv.ID_CLIENTE
LEFT JOIN VENTAS v 
    ON cv.ID_VENTA = v.ID_VENTA
LEFT JOIN CITAS ci 
    ON m.ID_MASCOTA = ci.ID_MASCOTA
LEFT JOIN MEDICOS_CITAS mc 
    ON ci.ID_CITA = mc.ID_CITA
LEFT JOIN MEDICOS med 
    ON mc.ID_MEDICO = med.ID_MEDICO;
/

/*Update de SP_registrar_usuario y tabla*/
ALTER TABLE USUARIO ADD (
  PRIMER_APELLIDO  VARCHAR2(50),
  SEGUNDO_APELLIDO VARCHAR2(50)
);

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_USUARIO (
  P_NOMBRE          IN VARCHAR2,
  P_PRIMER_APELLIDO IN VARCHAR2,
  P_SEGUNDO_APELLIDO IN VARCHAR2,
  P_USERNAME        IN VARCHAR2,
  P_PASS            IN VARCHAR2,
  P_ROL             IN VARCHAR2 DEFAULT 'OPERADOR'
)
IS
  V_ID NUMBER;
BEGIN
  IF P_NOMBRE IS NULL OR TRIM(P_NOMBRE) = '' THEN
    RAISE_APPLICATION_ERROR(-20010, 'El nombre no puede estar vacío');
  ELSIF P_PRIMER_APELLIDO IS NULL OR TRIM(P_PRIMER_APELLIDO) = '' THEN
    RAISE_APPLICATION_ERROR(-20011, 'El primer apellido no puede estar vacío');
  ELSIF P_SEGUNDO_APELLIDO IS NULL OR TRIM(P_SEGUNDO_APELLIDO) = '' THEN
    RAISE_APPLICATION_ERROR(-20012, 'El segundo apellido no puede estar vacío');
  ELSIF P_USERNAME IS NULL OR TRIM(P_USERNAME) = '' THEN
    RAISE_APPLICATION_ERROR(-20013, 'El usuario no puede estar vacío');
  ELSIF P_PASS IS NULL OR TRIM(P_PASS) = '' THEN
    RAISE_APPLICATION_ERROR(-20014, 'La contraseña no puede estar vacía');
  END IF;

  V_ID := SEQ_USUARIO.NEXTVAL;

  INSERT INTO USUARIO (
    ID_USUARIO, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, NOMBRE_USUARIO, CONTRASENA, ROL
  )
  VALUES (
    V_ID, P_NOMBRE, P_PRIMER_APELLIDO, P_SEGUNDO_APELLIDO, P_USERNAME, P_PASS, NVL(P_ROL,'OPERADOR')
  );

  DBMS_OUTPUT.PUT_LINE('Usuario registrado. ID=' || V_ID);

EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    RAISE_APPLICATION_ERROR(-20015, 'Ya existe un usuario con ese nombre');
END;
/

