/*Creación de tablespace. Separar y Organizar físicamente los datos del proyecto HappyPaws Veterinaria*/ 

CREATE TABLESPACE TS_HAPPYPAWS
DATAFILE 'C:\ORACLEDB\ORADATA\ORCL\TS_HAPPYPAWS01.DBF'
SIZE 200M
AUTOEXTEND ON NEXT 50M MAXSIZE 2G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;



/*EVIDENCIA: confirmar que el tablespace existe*/
SELECT TABLESPACE_NAME, STATUS, CONTENTS
FROM DBA_TABLESPACES
WHERE TABLESPACE_NAME = 'TS_HAPPYPAWS';

/*EVIDENCIA: confirmar el datafile y tamaño del tablespace*/
SELECT TABLESPACE_NAME, FILE_NAME, BYTES/1024/1024 AS MB, AUTOEXTENSIBLE
FROM DBA_DATA_FILES
WHERE TABLESPACE_NAME = 'TS_HAPPYPAWS';

/***************************/

/*Creación de roles y usuarios de la veterinaria. Separar responsabilidades (dueño, operador, consulta)*/

/*Creación de roles*/

CREATE ROLE ROL_HP_OWNER;      /* dueño del esquema (crea objetos)      */
CREATE ROLE ROL_HP_OPERADOR;   /* usuario operativo (manejo de datos)  */
CREATE ROLE ROL_HP_CONSULTA;   /* usuario de lectura (reportes)       */

/*Privilegios básicos por rol*/

GRANT CREATE SESSION TO ROL_HP_OWNER;
GRANT CREATE TABLE TO ROL_HP_OWNER;
GRANT CREATE VIEW TO ROL_HP_OWNER;
GRANT CREATE SEQUENCE TO ROL_HP_OWNER;
GRANT CREATE PROCEDURE TO ROL_HP_OWNER;
GRANT CREATE TRIGGER TO ROL_HP_OWNER;
GRANT CREATE SESSION TO ROL_HP_OPERADOR;
GRANT CREATE SESSION TO ROL_HP_CONSULTA;

/* Usuarios (Cada uno con su función)*/

CREATE USER HP_OWNER
IDENTIFIED BY "ProyectoGrupo2026!"
DEFAULT TABLESPACE TS_HAPPYPAWS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TS_HAPPYPAWS;   /* Puede crear tablas dentro del TS */

CREATE USER HP_OPERADOR
IDENTIFIED BY "ProyectoGrupo2026!"
DEFAULT TABLESPACE TS_HAPPYPAWS
TEMPORARY TABLESPACE TEMP
QUOTA 0 ON TS_HAPPYPAWS;           /* No crea objetos, solo usa datos */

CREATE USER HP_CONSULTA
IDENTIFIED BY "ProyectoGrupo2026!"
DEFAULT TABLESPACE TS_HAPPYPAWS
TEMPORARY TABLESPACE TEMP
QUOTA 0 ON TS_HAPPYPAWS;           /* Solo lectura */

/*Asignar roles a usuarios*/

GRANT ROL_HP_OWNER TO HP_OWNER;
GRANT ROL_HP_OPERADOR TO HP_OPERADOR;
GRANT ROL_HP_CONSULTA TO HP_CONSULTA;

/*EVIDENCIA: validar usuarios y tablespace por defecto*/
SELECT USERNAME, DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE
FROM DBA_USERS
WHERE USERNAME IN ('HP_OWNER','HP_OPERADOR','HP_CONSULTA');

/*EVIDENCIA: validar roles asignados */
SELECT GRANTEE, GRANTED_ROLE
FROM DBA_ROLE_PRIVS
WHERE GRANTEE IN ('HP_OWNER','HP_OPERADOR','HP_CONSULTA')
ORDER BY GRANTEE, GRANTED_ROLE;
